# **Predicting house prices**

# **1. Dataset description** 

Number of Attributes: 4 textual attributes in addition to the visual attributes that can be extracted from the images.

Attribute Information:
- Number of bedrooms
- Number of bathrooms
- Area (i.e., square footage)
- Zip code

For more info and credits visit:\
https://github.com/omarsayed7/House-price-estimation-from-visual-and-textual-features

<a id="Libraries"></a> <br>
# **2. Libraries and data**

In [ ]:
import warnings 
from collections import Counter 
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [ ]:
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
link = 'https://drive.google.com/file/d/1Ithoy81UTGXRMdAtENRTSrs97QFJmqko/view?usp=sharing' 

id = link.split("/")[-2]
filename= 'HousesInfo.txt'
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile(filename)

In [ ]:
header = ['bedrooms', 'bathrooms', 'area', 'zipcode', 'price']
df = pd.read_csv(filename, header=None, delimiter=' ', names=header)

<a id="Known"></a> <br>
# **3. First look at the data**

In [ ]:
#Searching for null values,data types and shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   bedrooms   535 non-null    int64
 1   bathrooms  535 non-null    float64
 2   area       535 non-null    int64
 3   zipcode    535 non-null    int64
 4   price      535 non-null    int64
dtypes: float64(1), int64(4)
memory usage: 21.0 KB

In [ ]:
#Looking at unique values
df.nunique()

bedrooms       9
bathrooms     14
area         435
zipcode       49
price        369
dtype: int64

In [ ]:
#Looking at a data sample
df.head()

   bedrooms  bathrooms  area  zipcode   price
0         4     4.0000  4053    85255  869500
1         4     3.0000  3343    36372  865200
2         3     4.0000  3923    85266  889000
3         5     5.0000  4022    85262  910000
4         3     4.0000  4116    85266  971226

# **4. Feature Engineering** <a id="Feature Engineering"></a> <br>

## Null treatement

## Treatement of Categorical variables

## Looking at the correlation of the data